name: CandyMania
author: JasonHaxStuff
version: 1.5
main: me.jasonhaxstuff.candymania.Main
description: Candy in Minecraft
commands:
    bliss:
        description: "Gives you Bliss. usage: /bliss  <amount>"
        permission: candy.bliss.give
    chocolate:
        description: "Gives you Chocolate. usage: /chocolate  <amount>"
        permission: candy.chocolate.give
    funbar:
        description: "Gives you a FunBar. usage: /funbar  <amount>"
        permission: candy.funbar.give
    tylenol:
        description: "Gives you Tylenol. usage: /tylenol  <amount>"
        permission: candy.tylenol.give